### ISSUE TITLE
Website Inspirations

### ISSUE THREAD

**Issue by lacraft** [CSC307Fall2018/TeemSicks#2]
Post links and a quick comment about why you like the website you found

**Comment by lacraft** [comment]
https://www.bikenashbar.com
I like the emphasis on the discounted products, I remember he said he wanted to make sure people saw the discounted items to help him sell those

**Comment by andrewpuleo** [comment]
https://www.foothillcyclery.com/
Local Bike Shop
Direct Competitor
Modern Design
